version: '3.8'

services:
  postgres:
    build:
      context: postgres/.
    container_name: petclinic-postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: petclinic
    ports:
      - "5432:5432"          # Expose PostgreSQL port
    networks:
      - petclinic-network

  petclinic:
    build:
      context: .             # Path to the app folder with the Spring PetClinic Dockerfile
    container_name: petclinic-app
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://petclinic-postgres:5432/petclinic  # PostgreSQL URL
      SPRING_DATASOURCE_USERNAME: user      # PostgreSQL username
      SPRING_DATASOURCE_PASSWORD: pass      # PostgreSQL password
      SPRING_PROFILES_ACTIVE: postgres      # Use PostgreSQL profile in Spring Boot
    ports:
      - "8080:8080"           # Expose PetClinic app on port 8080
    depends_on:
      - postgres              # Ensure PostgreSQL starts first
    networks:
      - petclinic-network

networks:
  petclinic-network:
    driver: bridge

