apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-petclinic-postgres
  labels:
    app: spring-petclinic-postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spring-petclinic-postgres
  template:
    metadata:
      labels:
        app: spring-petclinic-postgres
    spec: 
      containers:
        - name: postgres-container
          image: akhilmylaram/spring-petclinic-postgres:latest
          ports:
            - name: postgres-cont
              containerPort: 5432
          env:
            - name: POSTGRES_USER
              valueFrom:
                configMapKeyRef:
                  name: spring-petclinic-config
                  key: POSTGRES_USER

            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: spring-petclinic-secret
                  key: POSTGRES_PASSWORD

            - name:  POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  name: spring-petclinic-config
                  key: POSTGRES_DB
              
