apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-petclinic-app
  labels:
    app: spring-petclinic-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spring-petclinic-app
  template:
    metadata:
      labels:
        app: spring-petclinic-app
    spec:
      containers:
        - name: spring-petclinic-container
          image: akhilmylaram/spring-petclinic-app:latest
          ports:
            - name: app-port
              containerPort: 8080
          env:
            - name: SPRING_DATASOURCE_URL
              valueFrom:
                configMapKeyRef:
                  name: spring-petclinic-config
                  key: SPRING_DATASOURCE_URL

            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                configMapKeyRef:
                  name: spring-petclinic-config
                  key: SPRING_DATASOURCE_USERNAME

            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: spring-petclinic-secret
                  key: SPRING_DATASOURCE_PASSWORD

            - name: SPRING_PROFILES_ACTIVE
              valueFrom:
                configMapKeyRef:
                  name: spring-petclinic-config
                  key: SPRING_PROFILES_ACTIVE
              
              
             
