apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-petclinic-app
  labels:
    app: spring-petclinic-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spring-petclinic-app
  template:
    metadata:
      labels:
        app: spring-petclinic-app
    spec:
      containers:
        - name: spring-petclinic-container
          image: akhilmylaram/spring-petclinic-app:latest
          ports:
            - name: app-port
              containerPort: 8080
          env:
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://petclinic-postgres:5432/petclinic
            - name: SPRING_DATASOURCE_USERNAME
              value: user
            - name: SPRING_DATASOURCE_PASSWORD
              value: pass
            - name: SPRING_PROFILES_ACTIVE
              value: postgres
              
              
             
