apiVersion: v1
kind: Service
metadata: 
  name: petclinic-postgres
spec:
  ports:
    - port: 5432
      targetPort: 5432
      protocol: TCP
  type: ClusterIP
  selector:
    app: spring-petclinic-postgres
