apiVersion: v1
kind: Service
metadata:
  name: spring-petclinic-app-svc
spec:
  ports:
    - port: 8090
      targetPort: 8080
      nodePort: 30001
      protocol: TCP
  type: NodePort
  selector:
    app: spring-petclinic-app
