apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  labels:
    app: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend-container
          image: 
          ports:
            - name: frontend-port
              container_port: 3000
          
---

apiVersion: v1
kind: Service
metadata:
  name: frontend-svc
spec:
  ports:
    - port: 3000
      targetPort: 3000
      protocol: TCP
  type: ClusterIP
  selector:
    app: frontend

---

apiVersion: backend
kind: Deployment
metadata:
  name: backend
  labels:
    app: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend-container
          image: 
          ports:
            - name: backend-port
              containerPort: 5000
          env:
            - name: REDIS_HOST
              value: redis
            - name: REDIS_PORT
              value: 6379
            - name: REDIS_ENDPOINT_ip
              value: 
---

apiVersion: v1
kind: Service
metadata:
  name: backend-svc
spec:
  ports:
    - port: 6379
      targetPort: 6379
      protocol: TCP
  type: ClusterIP
  selector:
    app: backend
    
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  labels:
    app: redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
        - name: redis
          image: redis
          port:
            - name: redis-port
              containerPort: 6379
              
---
apiVersion: v1
kind: Service
metadata:
  name: redis
spec:
  ports:
    - port: 6379
      targetPort: 6379
      protocol: TCP
  type: ClusterIP
  selector:
    app: redis

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  labels:
    app: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx-container
          image: 
          ports: 
            - name: nginx-port
              containerPort: 80
              
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-svc
spec: 
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      nodePort: 30001
  type: NodePort
  selector:
    app: nginx
